title: Uploaded Fairy
description: Uploaded Fairy is a post apocalyptic webcomic with elements of historical and science fiction. Hemato-Tomato is an apprentice to her father, a state executioner, who must decide whether to pursue justice or love. One hundred years in the future, after France and Japan left the US, a young Nadine finds a mysterious game that takes her to a fully emmersive fantasy-world environment. But there is something wrong. A voice similar to her drives her actions in ways she does not desire.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
